# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161112_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
