# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='delete',
            new_name='delete_db',
        ),
    ]
