# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20161114_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='webpull',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
