# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_artist_webpull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='picture_of_artist',
        ),
    ]
