# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_artist_times_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='times_called',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
