# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20161126_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='level',
            field=models.FloatField(default=0),
        ),
    ]
