# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_artist_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='year_formed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
