# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20161202_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
