# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20161202_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
